In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Documents\Data analysis\Project\Amazon Sale Report.csv")

C:\Users\gjana\AppData\Local\Temp\ipykernel_9204\3023822748.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Documents\Data analysis\Project\Amazon Sale Report.csv")

In [3]:
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [4]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [5]:
df.shape

(128975, 24)

In [6]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [8]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [9]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [10]:
df = df.drop(columns=["index","Unnamed: 22"])

In [11]:
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,1,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,1,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,1,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,1,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,1,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN

In [12]:
df.shape

(128975, 22)

In [13]:
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [14]:
df["Date"]=pd.to_datetime(df["Date"], format="%m-%d-%y")

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  object
 16  ship-state          128942 non-null  object
 17  ship-postal-code    128942 non-null  float64
 18  ship-country        128942 non-null  object
 19  promotion-ids       79822 non-null   object
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(17)
memory usage: 20.8+ MB

In [16]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN

In [17]:
df["Year"]= df["Date"].dt.year

In [18]:
df["Month"]= df["Date"].dt.month
df["Month_Name"]= df["Date"].dt.month_name()

In [19]:
df["Day"] = df["Date"].dt.day
df["Day_Name"] = df["Date"].dt.day_name()
df["Quarter"] = df["Date"].dt.quarter

In [20]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,IN,NaN,False,Easy Ship,2022,4,April,30,Saturday,2
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,4,April,30,Saturday,2
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,2022,4,April,30,Saturday,2
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,IN,NaN,False,Easy Ship,2022,4,April,30,Saturday,2
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,IN,NaN,False,NaN,2022,4,April,30,Saturday,2

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  object
 16  ship-state          128942 non-null  object
 17  ship-postal-code    128942 non-null  float64
 18  ship-country        128942 non-null  object
 19  promotion-ids       79822 non-null   object
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   object
 22  Year                128975 non-null  int32
 23  Month               128975 non-null  int32
 24  Month_Name          128975 non-null  object
 25  Day                 128975 non-null  int32
 26  Day_Name            128975 non-null  object
 27  Quarter             128975 non-null  int32
dtypes: bool(1), datetime64[ns](1), float64(2), int32(4), int64(1), object(19)
memory usage: 24.7+ MB

# Investigate Amount

In [22]:
df[df["Amount"].isnull()][["Order ID","Status","Qty","Amount","Courier Status"]].head(20)

                Order ID     Status  Qty  Amount Courier Status
8    407-5443024-5233168  Cancelled    0     NaN      Cancelled
29   404-5933402-8801952  Cancelled    0     NaN            NaN
65   171-4137548-0481151  Cancelled    0     NaN      Cancelled
84   403-9950518-0349133  Cancelled    0     NaN      Cancelled
95   405-9112089-3379536  Cancelled    0     NaN      Cancelled
101  402-7841951-1872363  Cancelled    0     NaN      Cancelled
132  171-0293372-4913973  Cancelled    0     NaN      Cancelled
139  403-6442534-2769112  Cancelled    0     NaN      Cancelled
155  402-8078642-8565124  Cancelled    0     NaN      Cancelled
165  406-0218328-1773963  Cancelled    0     NaN      Cancelled
205  403-4337144-0984323  Cancelled    0     NaN      Cancelled
215  403-5456917-5571511  Cancelled    0     NaN      Cancelled
242  404-0634392-1837110  Cancelled    0     NaN      Cancelled
249  404-8514200-3544346  Cancelled    0     NaN      Cancelled
250  404-7452877-2137949  Cancelled    0     NaN            NaN
271  404-1607808-0769930  Cancelled    0     NaN      Cancelled
328  402-1365379-0131533  Cancelled    0     NaN      Cancelled
363  171-9620288-8918704  Cancelled    0     NaN      Cancelled
381  404-4026534-0431517  Cancelled    0     NaN      Cancelled
413  171-5542306-9306709  Cancelled    0     NaN      Cancelled

# Investigate Courier Status

In [23]:
df[df["Courier Status"].isnull()][["Order ID","Status","Qty","Courier Status"]].head(20)

                Order ID     Status  Qty Courier Status
0    405-8078784-5731545  Cancelled    0            NaN
3    403-9615377-8133951  Cancelled    0            NaN
23   404-6019946-2909948  Cancelled    0            NaN
29   404-5933402-8801952  Cancelled    0            NaN
83   404-6522553-9345930  Cancelled    0            NaN
178  171-1224053-5752314  Cancelled    0            NaN
226  407-4936046-5852304  Cancelled    0            NaN
227  407-4936046-5852304  Cancelled    0            NaN
250  404-7452877-2137949  Cancelled    0            NaN
251  402-2703790-2816329  Cancelled    0            NaN
270  407-5600921-2143569  Cancelled    0            NaN
324  407-5096970-7475550  Cancelled    0            NaN
327  407-9707366-3029944  Cancelled    0            NaN
380  404-6026001-1717923  Cancelled    0            NaN
404  404-5848202-7366725  Cancelled    0            NaN
415  404-5867260-9073129  Cancelled    0            NaN
437  171-4643830-2345965  Cancelled    0            NaN
510  402-1721558-6618710  Cancelled    0            NaN
537  408-5823964-2421167  Cancelled    0            NaN
538  408-2752424-0976355  Cancelled    0            NaN

# Investigate fulfilled-by

In [24]:
df[df["fulfilled-by"].isnull()][["Order ID","Fulfilment","fulfilled-by"]].head(20)

               Order ID Fulfilment fulfilled-by
2   404-0687676-7273146     Amazon          NaN
4   407-1069790-7240320     Amazon          NaN
5   404-1490984-4578765     Amazon          NaN
6   408-5748499-6859555     Amazon          NaN
8   407-5443024-5233168     Amazon          NaN
9   402-4393761-0311520     Amazon          NaN
10  407-5633625-6970741     Amazon          NaN
11  171-4638481-6326716     Amazon          NaN
13  408-7955685-3083534     Amazon          NaN
16  406-9379318-6555504     Amazon          NaN
17  405-9013803-8009918     Amazon          NaN
19  405-5957858-1051546     Amazon          NaN
20  405-0607769-0716360     Amazon          NaN
21  404-8494550-5860325     Amazon          NaN
22  171-1305077-2813934     Amazon          NaN
24  402-3384087-4005164     Amazon          NaN
27  408-3484251-6901959     Amazon          NaN
28  405-7755803-4729935     Amazon          NaN
30  171-9040274-9291563     Amazon          NaN
31  403-7056319-0979561     Amazon          NaN

# Investigate promotion-ids

In [25]:
df[df["promotion-ids"].isnull()][["Order ID", "promotion-ids"]].head(20)

               Order ID promotion-ids
0   405-8078784-5731545           NaN
3   403-9615377-8133951           NaN
4   407-1069790-7240320           NaN
9   402-4393761-0311520           NaN
10  407-5633625-6970741           NaN
11  171-4638481-6326716           NaN
13  408-7955685-3083534           NaN
17  405-9013803-8009918           NaN
19  405-5957858-1051546           NaN
22  171-1305077-2813934           NaN
23  404-6019946-2909948           NaN
27  408-3484251-6901959           NaN
29  404-5933402-8801952           NaN
34  404-7774085-3780319           NaN
39  403-4242957-8599555           NaN
44  402-7595162-9129931           NaN
46  408-3917043-5314763           NaN
53  402-1752649-2274748           NaN
57  406-8879861-2081117           NaN
64  407-2974257-4781134           NaN

# Investigate Missing Shopping Information

In [26]:
df[df["ship-state"].isnull()][["Order ID", "Status", "ship-city", "ship-state", "ship-country"]]

,Order ID,Status,ship-city,ship-state,ship-country
1871,404-0566904-4825137,Shipped,NaN,NaN,NaN
1872,404-0566904-4825137,Shipped,NaN,NaN,NaN
8752,406-4003386-8768363,Shipped,NaN,NaN,NaN
11215,402-0107720-7057168,Shipped,NaN,NaN,NaN
13252,407-4532637-8415521,Cancelled,NaN,NaN,NaN
15688,404-9229894-8608305,Shipped,NaN,NaN,NaN
16787,402-4919636-4333150,Shipped - Delivered to Buyer,NaN,NaN,NaN
18351,405-4927647-8064368,Shipped,NaN,NaN,NaN
22930,402-8628677-0457954,Shipped - Returned to Seller,NaN,NaN,NaN
24986,406-4079063-8291520,Cancelled,NaN,NaN,NaN
30379,404-7506843-7913132,Shipped - Delivered to Buyer,NaN,NaN,NaN
37963,407-3064376-9158743,Cancelled,NaN,NaN,NaN
37964,407-3064376-9158743,Cancelled,NaN,NaN,NaN
60986,171-3257610-9237139,Shipped - Delivered to Buyer,NaN,NaN,NaN
63040,402-1049475-3611523,Shipped,NaN,NaN,NaN
73675,405-1356730-8598722,Shipped - Delivered to Buyer,NaN,NaN,NaN
73746,407-4664354-2179554,Shipped,NaN,NaN,NaN
73771,406-7680604-5439529,Shipped,NaN,NaN,NaN
73772,406-7680604-5439529,Shipped,NaN,NaN,NaN
73911,405-3420451-5230744,Cancelled,NaN,NaN,NaN
80011,171-4552355-0255565,Shipped - Returned to Seller,NaN,NaN,NaN
80092,403-2857451-7335536,Shipped,NaN,NaN,NaN
80455,171-4691098-8489159,Shipped - Delivered to Buyer,NaN,NaN,NaN
84008,405-8605864-8021901,Shipped - Returned to Seller,NaN,NaN,NaN
84757,402-8651786-0683548,Shipped,NaN,NaN,NaN
104201,403-3190636-2013146,Shipped - Delivered to Buyer,NaN,NaN,NaN
106498,402-8673941-7883531,Cancelled,NaN,NaN,NaN
124215,405-0340492-2359532,Cancelled,NaN,NaN,NaN
124357,405-5884153-9925116,Shipped,NaN,NaN,NaN
124358,405-5884153-9925116,Shipped,NaN,NaN,NaN
124359,405-5884153-9925116,Shipped,NaN,NaN,NaN
125385,403-5172380-9787567,Shipped,NaN,NaN,NaN
126620,403-4249038-6582716,Shipped - Delivered to Buyer,NaN,NaN,NaN

In [27]:
df["Amount"]=df["Amount"].fillna(0)

In [28]:
df["Courier Status"]=df["Courier Status"].fillna("Cancelled")

In [29]:
df["fulfilled-by"]=df["fulfilled-by"].fillna("Amazon")

In [30]:
df["promotion-ids"]=df["promotion-ids"].fillna("No Promotion")

In [31]:
df["ship-city"] = df["ship-city"].fillna("Unknown")
df["ship-state"] = df["ship-state"].fillna("Unknown")
df["ship-country"] = df["ship-country"].fillna("Unknown")

In [32]:
df["ship-postal-code"] = df["ship-postal-code"].fillna(0)

In [33]:
df.isnull().sum()

Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Style                    0
SKU                      0
Category                 0
Size                     0
ASIN                     0
Courier Status           0
Qty                      0
currency              7795
Amount                   0
ship-city                0
ship-state               0
ship-postal-code         0
ship-country             0
promotion-ids            0
B2B                      0
fulfilled-by             0
Year                     0
Month                    0
Month_Name               0
Day                      0
Day_Name                 0
Quarter                  0
dtype: int64

In [34]:
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,IN,No Promotion,False,Easy Ship,2022,4,April,30,Saturday,2
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,4,April,30,Saturday,2
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,Amazon,2022,4,April,30,Saturday,2
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,IN,No Promotion,False,Easy Ship,2022,4,April,30,Saturday,2
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,IN,No Promotion,False,Amazon,2022,4,April,30,Saturday,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,IN,No Promotion,False,Amazon,2022,5,May,31,Tuesday,2
128971,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2
128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,IN,No Promotion,False,Amazon,2022,5,May,31,Tuesday,2
128973,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2
128974,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2

In [35]:
pd.set_option('display.max.columns',28)

In [36]:
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,Cancelled,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,No Promotion,False,Easy Ship,2022,4,April,30,Saturday,2
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,4,April,30,Saturday,2
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,Amazon,2022,4,April,30,Saturday,2
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,Cancelled,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,No Promotion,False,Easy Ship,2022,4,April,30,Saturday,2
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,No Promotion,False,Amazon,2022,4,April,30,Saturday,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,Shipped,1,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,No Promotion,False,Amazon,2022,5,May,31,Tuesday,2
128971,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,B09VC6KHX8,Shipped,1,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2
128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,Shipped,1,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,No Promotion,False,Amazon,2022,5,May,31,Tuesday,2
128973,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,B0894Y2NJQ,Shipped,1,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2
128974,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,B0894X27FC,Shipped,1,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2

In [37]:
df["currency"]=df["currency"].fillna('INR')

In [38]:
df.isnull()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
128971,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
128972,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
128973,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
128974,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [39]:
df.isnull().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
promotion-ids         0
B2B                   0
fulfilled-by          0
Year                  0
Month                 0
Month_Name            0
Day                   0
Day_Name              0
Quarter               0
dtype: int64

In [40]:
df["Order ID"].duplicated().sum()

np.int64(8597)

In [41]:
df[df["Order ID"].duplicated(keep=False)].sort_values("Order ID").head(20)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
78939,171-0012693-2893106,2022-05-07,Cancelled,Merchant,Amazon.in,Standard,NW015,NW015-TP-PJ-S,Set,S,B0922SCDFN,Cancelled,0,INR,477.14,SRI GANGANAGAR,RAJASTHAN,335001.0,IN,No Promotion,False,Easy Ship,2022,5,May,7,Saturday,2
78938,171-0012693-2893106,2022-05-07,Cancelled,Merchant,Amazon.in,Standard,NW030,NW030-TP-PJ-S,Set,S,B09G2RFP14,Cancelled,0,INR,538.10,SRI GANGANAGAR,RAJASTHAN,335001.0,IN,No Promotion,False,Easy Ship,2022,5,May,7,Saturday,2
91476,171-0014231-7760344,2022-06-29,Pending,Amazon,Amazon.in,Expedited,J0224,J0224-SKD-XS,Set,XS,B09RKFBZZD,Unshipped,1,INR,1364.00,AHMEDABAD,Gujarat,380015.0,IN,No Promotion,False,Amazon,2022,6,June,29,Wednesday,2
91475,171-0014231-7760344,2022-06-29,Pending,Amazon,Amazon.in,Expedited,SET342,SET342-KR-NP-N-XS,Set,XS,B09Q1943PQ,Shipped,1,INR,850.00,AHMEDABAD,Gujarat,380015.0,IN,No Promotion,False,Amazon,2022,6,June,29,Wednesday,2
24515,171-0015435-1981904,2022-04-16,Shipped,Amazon,Amazon.in,Expedited,JNE3611,JNE3611-KR-L,kurta,L,B08XVQMSJV,Shipped,1,INR,459.00,Pimpri Chinchwad,MAHARASHTRA,412101.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,4,April,16,Saturday,2
24516,171-0015435-1981904,2022-04-16,Shipped,Amazon,Amazon.in,Expedited,JNE3794,JNE3794-KR-L,kurta,L,B09HMSSM5B,Shipped,1,INR,517.00,Pimpri Chinchwad,MAHARASHTRA,412101.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,4,April,16,Saturday,2
99357,171-0019960-6156301,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,SET334,SET334-KR-NP-XXXL,Set,3XL,B09KXVBJ19,Shipped,1,INR,626.00,BENGALURU,KARNATAKA,560084.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,6,June,22,Wednesday,2
99358,171-0019960-6156301,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,SET331,SET331-KR-NP-XXXL,Set,3XL,B09NQ4C51C,Shipped,1,INR,635.00,BENGALURU,KARNATAKA,560084.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,6,June,22,Wednesday,2
123553,171-0031114-0715560,2022-06-04,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3401,JNE3401-KR-XXL,kurta,XXL,B082W7S1S8,Shipped,1,INR,301.00,MUMBAI,MAHARASHTRA,400093.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,6,June,4,Saturday,2
123554,171-0031114-0715560,2022-06-04,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3425,JNE3425-KR-XL,kurta,XL,B083178GTW,Shipped,1,INR,333.00,MUMBAI,MAHARASHTRA,400093.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,6,June,4,Saturday,2
55351,171-0032816-1151573,2022-05-27,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3652,JNE3652-TP-N-L,Top,L,B08ZHKRV5F,Shipped,1,INR,338.00,GURGAON,HARYANA,122002.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,5,May,27,Friday,2
55352,171-0032816-1151573,2022-05-27,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,NW037,NW037-TP-SR-M,Set,M,B099NSJG7Z,Shipped,1,INR,450.00,GURGAON,HARYANA,122002.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,5,May,27,Friday,2
34983,171-0035451-9642759,2022-04-09,Shipped,Amazon,Amazon.in,Expedited,J0090,J0090-TP-S,Top,S,B092D3276L,Shipped,1,INR,563.00,AHMEDABAD,Gujarat,382470.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,4,April,9,Saturday,2
34984,171-0035451-9642759,2022-04-09,Shipped,Amazon,Amazon.in,Expedited,J0084,J0084-TP-S,Top,S,B09C87JBSV,Shipped,1,INR,560.00,AHMEDABAD,Gujarat,382470.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,4,April,9,Saturday,2
109700,171-0036605-7601963,2022-06-14,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET342,SET342-KR-NP-N-L,Set,L,B09Q18BBWR,Shipped,1,INR,850.00,NEW DELHI,DELHI,110034.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,6,June,14,Tuesday,2
109701,171-0036605-7601963,2022-06-14,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET402,SET402-KR-NP-L,Set,L,B09VC63Y2N,Shipped,1,INR,988.00,NEW DELHI,DELHI,110034.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,6,June,14,Tuesday,2
74295,171-0040661-6643541,2022-05-11,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET323,SET323-KR-NP-XL,Set,XL,B09NDKKM7P,Shipped,1,INR,999.00,ELURU,ANDHRA PRADESH,534001.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,5,May,11,Wednesday,2
74296,171-0040661-6643541,2022-05-11,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET401,SET401-KR-NP-L,Set,L,B09VC5ZGD8,Cancelled,0,INR,0.00,ELURU,ANDHRA PRADESH,534001.0,IN,No Promotion,False,Easy Ship,2022,5,May,11,Wednesday,2
87313,171-0056896-3348311,2022-05-02,Shipped,Amazon,Amazon.in,Expedited,SET380,SET380-KR-NP-XXXL,Set,3XL,B09QJ3F6T9,Shipped,1,INR,965.00,GURGAON,HARYANA,122018.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,2,Monday,2
87314,171-0056896-3348311,2022-05-02,Shipped,Amazon,Amazon.in,Expedited,SET388,SET388-KR-NP-XXXL,Set,3XL,B09QJMF9YB,Shipped,1,INR,1260.00,GURGAON,HARYANA,122018.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,2,Monday,2

In [42]:
df.duplicated().sum()

np.int64(6)

In [43]:
df[df.duplicated(keep=False)]

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
30660,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,B08B3YPD63,Cancelled,0,INR,0.0,Siliguri,WEST BENGAL,734008.0,IN,No Promotion,False,Amazon,2022,4,April,12,Tuesday,2
30661,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,B08B3YPD63,Cancelled,0,INR,0.0,Siliguri,WEST BENGAL,734008.0,IN,No Promotion,False,Amazon,2022,4,April,12,Tuesday,2
41291,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,M,B08MYVCDB4,Cancelled,0,INR,0.0,BENGALURU,KARNATAKA,560072.0,IN,No Promotion,False,Amazon,2022,4,April,5,Tuesday,2
41292,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,M,B08MYVCDB4,Cancelled,0,INR,0.0,BENGALURU,KARNATAKA,560072.0,IN,No Promotion,False,Amazon,2022,4,April,5,Tuesday,2
79844,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,L,B09KXRB7JV,Cancelled,0,INR,0.0,ERNAKULAM,KERALA,682017.0,IN,No Promotion,False,Amazon,2022,5,May,7,Saturday,2
79845,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,L,B09KXRB7JV,Cancelled,0,INR,0.0,ERNAKULAM,KERALA,682017.0,IN,No Promotion,False,Amazon,2022,5,May,7,Saturday,2
85790,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,B09NDKKM7P,Shipped,1,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,3,Tuesday,2
85791,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,B09NDKKM7P,Shipped,1,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,3,Tuesday,2
86418,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,3XL,B08YYQS8FH,Shipped,1,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,3,Tuesday,2
86419,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,3XL,B08YYQS8FH,Shipped,1,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,3,Tuesday,2
98954,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,B08XNJG8B1,Shipped,1,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,6,June,22,Wednesday,2
98955,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,B08XNJG8B1,Shipped,1,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,6,June,22,Wednesday,2

In [44]:
df.drop_duplicates(inplace=True)

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.shape

(128969, 28)

In [49]:
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Year,Month,Month_Name,Day,Day_Name,Quarter
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,Cancelled,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,No Promotion,False,Easy Ship,2022,4,April,30,Saturday,2
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,2022,4,April,30,Saturday,2
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,Amazon,2022,4,April,30,Saturday,2
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,Cancelled,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,No Promotion,False,Easy Ship,2022,4,April,30,Saturday,2
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,No Promotion,False,Amazon,2022,4,April,30,Saturday,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,Shipped,1,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,No Promotion,False,Amazon,2022,5,May,31,Tuesday,2
128971,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,B09VC6KHX8,Shipped,1,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2
128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,Shipped,1,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,No Promotion,False,Amazon,2022,5,May,31,Tuesday,2
128973,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,B0894Y2NJQ,Shipped,1,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2
128974,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,B0894X27FC,Shipped,1,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Amazon,2022,5,May,31,Tuesday,2

In [50]:
print(df["ship-state"].unique())

['MAHARASHTRA' 'KARNATAKA' 'PUDUCHERRY' 'TAMIL NADU' 'UTTAR PRADESH'
 'CHANDIGARH' 'TELANGANA' 'ANDHRA PRADESH' 'RAJASTHAN' 'DELHI' 'HARYANA'
 'ASSAM' 'JHARKHAND' 'CHHATTISGARH' 'ODISHA' 'KERALA' 'MADHYA PRADESH'
 'WEST BENGAL' 'NAGALAND' 'Gujarat' 'UTTARAKHAND' 'BIHAR'
 'JAMMU & KASHMIR' 'PUNJAB' 'HIMACHAL PRADESH' 'ARUNACHAL PRADESH'
 'MANIPUR' 'Goa' 'MEGHALAYA' 'GOA' 'TRIPURA' 'LADAKH' 'DADRA AND NAGAR'
 'SIKKIM' 'Delhi' 'Unknown' 'ANDAMAN & NICOBAR ' 'Punjab' 'Rajshthan'
 'Manipur' 'rajasthan' 'Odisha' 'NL' 'Bihar' 'MIZORAM' 'punjab'
 'New Delhi' 'Rajasthan' 'Punjab/Mohali/Zirakpur' 'Puducherry' 'delhi'
 'RJ' 'Chandigarh' 'orissa' 'LAKSHADWEEP' 'goa' 'PB' 'APO'
 'Arunachal Pradesh' 'AR' 'Pondicherry' 'Sikkim' 'Arunachal pradesh'
 'Nagaland' 'bihar' 'Mizoram' 'rajsthan' 'Orissa' 'Rajsthan' 'Meghalaya']

In [51]:
df["ship-state"] = df["ship-state"].str.strip()

In [52]:
df["ship-state"]=df["ship-state"].str.title()

In [57]:
print(df["ship-state"].unique())

['Maharashtra' 'Karnataka' 'Puducherry' 'Tamil Nadu' 'Uttar Pradesh'
 'Chandigarh' 'Telangana' 'Andhra Pradesh' 'Rajasthan' 'Delhi' 'Haryana'
 'Assam' 'Jharkhand' 'Chhattisgarh' 'Odisha' 'Kerala' 'Madhya Pradesh'
 'West Bengal' 'Nagaland' 'Gujarat' 'Uttarakhand' 'Bihar'
 'Jammu & Kashmir' 'Punjab' 'Himachal Pradesh' 'Arunachal Pradesh'
 'Manipur' 'Goa' 'Meghalaya' 'Tripura' 'Ladakh' 'Dadra And Nagar' 'Sikkim'
 'Unknown' 'Andaman & Nicobar' 'Rajshthan' 'Nl' 'Mizoram' 'New Delhi'
 'Punjab/Mohali/Zirakpur' 'Rj' 'Orissa' 'Lakshadweep' 'Pb' 'Apo' 'Ar'
 'Pondicherry' 'Rajsthan']

In [58]:
df[df["ship-state"].str.startswith("A", na=False)]["ship-state"].unique()

array(['Andhra Pradesh', 'Assam', 'Arunachal Pradesh',
       'Andaman & Nicobar', 'Apo', 'Ar'], dtype=object)

In [59]:
state_replace = {"Orissa":"Odisha","Ar":"Arunachal Pradesh","Rj":"Rajasthan",
    "Pb":"Punjab","Nl":"Nagaland","Ap":"Andhra Pradesh","Goa ":"Goa","Delhi ":"Delhi",
    "Unknown":"Unknown","Pondicherry":"Puducherry","Punjab/Mohali/Zirakpur":"Punjab"}

In [60]:
df["ship-state"] = df["ship-state"].replace(state_replace)

In [63]:
print(df["ship-state"].unique())

['Maharashtra' 'Karnataka' 'Puducherry' 'Tamil Nadu' 'Uttar Pradesh'
 'Chandigarh' 'Telangana' 'Andhra Pradesh' 'Rajasthan' 'Delhi' 'Haryana'
 'Assam' 'Jharkhand' 'Chhattisgarh' 'Odisha' 'Kerala' 'Madhya Pradesh'
 'West Bengal' 'Nagaland' 'Gujarat' 'Uttarakhand' 'Bihar'
 'Jammu & Kashmir' 'Punjab' 'Himachal Pradesh' 'Arunachal Pradesh'
 'Manipur' 'Goa' 'Meghalaya' 'Tripura' 'Ladakh' 'Dadra And Nagar' 'Sikkim'
 'Unknown' 'Andaman & Nicobar' 'Rajshthan' 'Mizoram' 'New Delhi'
 'Lakshadweep' 'Apo' 'Rajsthan']

In [64]:
state_replace = {"Rajshthan": "Rajasthan","Rajsthan": "Rajasthan","New Delhi": "Delhi","Dadra And Nagar": "Dadra & Nagar Haveli And Daman & Diu","Apo": "Unknown"}
df["ship-state"] = df["ship-state"].replace(state_replace)

In [66]:
print(df["ship-state"].nunique())

37

In [67]:
print(df["ship-city"].nunique())

8956

In [68]:
print(sorted(df["ship-city"].unique()))

['(Chikmagalur disterict).     (N.R pur thaluku)', '(Via Cuncolim)Quepem,South Goa', ',HYDERABAD', ',raibarely road faizabad (Ayodhya)', '..katra', '.Gannavaram', '.azamgarh', '1', '116  B. P. M. B SARANI, UTTARPARA KOTRUNG', '147/19 B Keshab Chandra Sen Street Kolkata nine ma', '53miles', '6th mile tadong', '7BARASAT', 'AAMBY VALLEY', 'ABHAYAPURI', 'ABHAYAPURI, Bongaigaon', 'ABOHAR', 'ABU ROAD', 'ACHALPUR', 'ACHAMPET', 'ACHANTA', 'ACHARAPAKKAM', 'ACHHNERA', 'ADALAJ', 'ADAMPUR', 'ADAPUR', 'ADBHAR', 'ADDAKAL', 'ADDANKI', 'ADICHANALLOOR', 'ADILABAD', 'ADINAD', 'ADIPUR, GANDHIDHAM', 'ADITYANA', 'ADITYAPUR', 'ADONI', 'ADOOR', 'ADOOR, vaddakkedathu cavu', 'ADRA', 'AFZALGARH', 'AGAR', 'AGAR Malwa', 'AGARTALA', 'AGATTI', 'AGIRIPALLE', 'AGRA', 'AGRA 282005', 'AHERI', 'AHIWARA', 'AHMADNAGAR', 'AHMADNAGARA', 'AHMADPUR', 'AHMED NAGAR', 'AHMEDABAD', 'AHMEDABAD 380007', 'AHMEDABAD 380013', 'AHMEDABAD 380014', 'AHMEDABAD,', 'AHMEDABADvasna', 'AHMEDABAd', 'AHMEDNAGAR', 'AHORE', 'AIMANAM', 'AIZAWL', 'AJAYGARH', 'AJEKAR', 'AJMER', 'AJNALA', 'AKALGARH', 'AKATHIYOOR', 'AKBARPUR', 'AKBARPUR NEAR KANPUR', 'AKHNOOR', 'AKIVIDU', 'AKKALKUWA', 'AKLUJ', 'AKOLA', 'AKOLE AHMADNAGAR DISTRICT', 'ALA', 'ALAGAPPAPURAM', 'ALAGAPPAPURAM,kanyakumari district', 'ALAMCODE MALAPPURAM DISTRICT', 'ALAMCODE Vanchiyoor THIRUVANANTHAPURAM DISTRICT', 'ALAMURU', 'ALAND', 'ALANGAYAM', 'ALANGULAM TIRUNELVELI DISTRICT', 'ALANTHURAI', 'ALAPPUZHA', 'ALAPPUZHA District', 'ALAPPUZHA harippad', 'ALATHUR', 'ALAWALPUR', 'ALDONA', 'ALIBAG', 'ALIGANG, LUCKNOW', 'ALIGANJ', 'ALIGARH', 'ALIPORE KOLKATA', 'ALIPURDUAR', 'ALIRAJPUR', 'ALLAHABAD', 'ALLAHABAD Prayagraj', 'ALLAHGANJ', 'ALLAPALLI', 'ALLAVARAM', 'ALLIPUR', 'ALLUR', 'ALMORA', 'ALNAVAR', 'ALOK CITY', 'ALONG', 'ALOT', 'ALTO PORVORIM,', 'ALUR', 'ALURU ,Hassan district', 'ALUVA', 'ALUVA, ERNAKULAM DIST', 'ALWAR', 'ALWARKURICHI', 'AMADALAVALASA', 'AMALAPURAM', 'AMALNER', 'AMANGAL', 'AMARAVATHI', 'AMARKANTAK', 'AMARPATAN', 'AMB', 'AMBAD', 'AMBAGARH CHOWKI', 'AMBALA', 'AMBALA CANTT', 'AMBALA CITY', 'AMBALA Cantt', 'AMBALA cantt', 'AMBARNATH', 'AMBARNATH (E)', 'AMBARNATH (East)', 'AMBARNATH East', 'AMBARNATH West', 'AMBARNATH, West', 'AMBASAMUDRAM', 'AMBATTUR', 'AMBEJOGAI', 'AMBEPUR', 'AMBIKANAGARA', 'AMBIKAPUR', 'AMBUR', 'AMDANGA', 'AMETHI', 'AMETHI SULTANPUR DISTRICT', 'AMGAON', 'AMILA', 'AMLA', 'AMLAI', 'AMMAPETTAI ERODE DISTRICT', 'AMMAPETTAI THANJAVUR DISTRICT', 'AMRAVATI', 'AMRELI', 'AMRITSAR', 'AMRITsar', 'AMROHA', 'AMTA', 'AMTALA', 'ANAIMALAI', 'ANAKAPALLE', 'ANAND', 'ANAND NAGAR', 'ANANDAPUR', 'ANANDNAGAR', 'ANANDPUR SAHIB', 'ANANTAPALLI', 'ANANTAPUR', 'ANANTHAPUR', 'ANANTNAG', 'ANANTPUR', 'ANAPARTHY', 'ANCHARAKANDY', 'ANDAR', 'ANDHERI EAST, MUMBAI', 'ANDHERI WEST, MUMBAI', 'ANDIPALAYAM', 'ANDIPATTI', 'ANDIPATTI JAKKAMPATTI', 'ANGAMALY', 'ANGUL', 'ANJANI PORTLAND CEMENT FACTORY', 'ANJAR', 'ANJUNA', 'ANJUNA Bardez Go', 'ANKLAV', 'ANKLESHWAR', 'ANKLESHWR', 'ANKOLA', 'ANNAMALAI NAGAR', 'ANNAMALAI NAGAR , CHIDHAMBARAM', 'ANNAVARAM', 'ANNUR', 'ANPARA', 'ANTAH', 'ANTHICAD', 'ANTHIYUR', 'ANUGUL', 'ANUPGARH', 'ANUPPUR', 'ANUPURAM', 'AONLA', 'APIIC TADA', 'APO', 'APPAKUDAL', 'ARA', 'ARAKANDANALLUR', 'ARAKONAM', 'ARALVAIMOZHI', 'ARAMBAGH', 'ARAMBOL', 'ARANI', 'ARANI THIRUVALLUR DISTRICT', 'ARANI TIRUVANNAMALAI DISTRICT', 'ARANTHANGI', 'ARARIA', 'ARASUR', 'ARCOT', 'ARERAJ', 'ARIYALLUR', 'ARIYALUR', 'ARJUNDA', 'ARKALGUD', 'ARKI', 'ARMOOR', 'ARMUR', 'ARNI', 'ARNIA', 'AROOR', 'ARRAH', 'ARSIKERE', 'ARUMBAVUR', 'ARUPPUKKOTTAI', 'ARVI', 'ARVI,Dist- wardha', 'ARWAL', 'ASANSOL', 'ASARGANJ', 'ASARIPALLAM', 'ASHOKNAGAR', 'ASHRAFPUR KICHHAUCHHA', 'ASHTA', 'ASHTI WARDHA DISTRICT', 'ASIKA', 'ASIND', 'ASSANDH', 'ATARRA', 'ATCHUTAPURAM APSEZ', 'ATELI', 'ATHIRAMPUZHA', 'ATHIYANNUR', 'ATHMALLIK', 'ATHNI', 'ATHOLI', 'ATHUR THOOTHUKKUDI DISTRICT', 'ATMAKUR', 'ATMAKUR  (M), Kurnool dist', 'ATMAKUR SRI POTTI SRIRAMULU', 'ATREYAPURAM', 'ATRU', 'ATTAYAMPATTI', 'ATTILLI', 'ATTINGAL', 'ATTUR', 'ATUL', 'ATUL dist. Valsad', 'AURAD', 'AURAIYA', 'AURANGABAD', 'AUSA', 'AUT', 'AVADI', 'AVALAPALLI', 'AVANIGADDA', 'AVERSA', 'AVINASHI', 'AVINISSERY', 'AVITTATHUR', 'AWALPUR, dist Chandrapur', 'AWANTIPORA', 'AYACODE', 'AYODHYA', 'AYOTHIAPATTINAM', 'AYYAMPALAYAM', 'AYYAMPETTAI THANJAVUR DISTRICT', 'AZAMGARH', 'AZARA', 'AZHIKODE', 'AZHIKODE ,kannur', 'AZHIYUR', 'Aalo', 'Abhayapuri', 'Abohar', 'Aburoad', 'Adajan Gam, Surat', 'Adambakkam', 'Adarsh Nagar, Jaipur', 'Addanki', 'Addanki mandal Bapatl District', 'Addision Nagar, Mangadu', 'Adilabad', 'Adimaly', 'Adipur', 'Adityapur/ Jamshedpur', 'Adoni', 'Adoor', 'Adra', 'Adyal', 'Afzalgarh', 'Agarpara', 'Agartala', 'Agarwada', 'Agorpara', 'Agra', 'Agra-282001', 'Ahemdabad', 'Ahemedabad', 'Aheri', 'Ahiwara', 'Ahmadabad', 'Ahmdabad', 'Ahmedabad', 'Ahmedabad.', 'Ahmedanagar', 'Ahmednagar', 'Ahmedpur', 'Ainavilli mandal, east godhavari', 'Airoli', 'Airoli Navi Mumbai', 'Airoli, Navimumbai', 'Aizawl', 'Ajmer', 'Akash nagar Annexe, Manimedu', 'Akbarpur', 'Akhnoor', 'Akola', 'Akot', 'Akurdi', 'Alaipur', 'Alamcode', 'Alandi', 'Alandi pune', 'Alandi, Pune', 'Alangad', 'Alangad via', 'Alappuzha', 'Alapuzha,kayamkullam', 'Alapuzhya', 'Aligarh', 'Alipurduar', 'Alipurduat', 'Allagadda', 'Allahabad', 'Allapra, Perumbavoor', 'Allapuzha', 'Almora', 'Along', 'Alto Dabolim', 'Alto Porvorim', 'Aluva', 'Aluva / Ernakulam', 'Aluva 6', 'Aluva Ernakulam', 'Aluva, Ernakulam', 'Aluva-2', 'Aluva2', 'Alwar', 'Alwarpet, Chennai', 'Amalapuram', 'Amalner', 'Amalsad', 'Amarpur', 'Amb', 'Ambala', 'Ambala Cantt', 'Ambala City', 'Ambala city', 'Ambalamedu', 'Ambalapuzha', 'Amballur', 'Ambarnath', 'Ambarnath (west)', 'Ambarnath East', 'Ambattur', 'Ambedkar Nagar', 'Ambedkar nagar', 'Ambedkarnager', 'Ambegaon', 'Ambernath', 'Ambernath East Dist Thane', 'Ambernath West', 'Ambernath [e] DISTRICT AMBERNATH', 'Amberpwt Hyderabad', 'Ambikapur', 'Ambur', 'Ameenpur Hyderabad', 'Amethi', 'Amethi,sultanpur', 'Amlohri', 'Ampati', 'Amrath', 'Amravati', 'Amravati.', 'Amreli', 'Amritsar', 'Amruthahalli, Jakkur Post', 'Amtady', 'Anakapalle', 'Anakapalli', 'Anakapalli mandal', 'Anakkayam', 'Anand', 'Anandpur sahib', 'Anantapur', 'Anantapur district', 'Ananthpur', 'Anantnag', 'Anchal', 'Andal', 'Andaman and nicobar islands port Blair', 'Andhari', 'Andheri', 'Andheri East, Mumbai', 'Andheri West, Mumbai', 'Andheri e', 'Andheri east', 'Andoorkonam, Trivandrum', 'Andul', 'Andul near maya stores', 'Andul, Howrah', 'Andul-mouri', 'Anekal', 'Angamaly', 'Angamaly, ernakulam', 'Angul', 'Anil neerkonda hospital', 'Anjangaon Surji', 'Anjar', 'Ankleshwar', 'Ankleshwar, Dist-Bharuch', 'Annamalai nagar, Chidambaram', 'Annamanada,Trissur', 'Anpara', 'Anpara,Sonebhadra', 'Anta city', 'Anthiyur', 'Anugul', 'Anuppur', 'Anupuram', 'Anushaktinagar, Mumbai', 'Aquem Margao', 'Ara', 'Aralvaimozhi', 'Arambagh', 'Arangottukara', 'Arariya', 'Arasu nager Pc Patti,theni', 'Arcot', 'Argul, Khordha', 'Ariyalur', 'Ariyalur D.T', 'Arki', 'Armoor', 'Armori', 'Armori, Dist. Gadchiroli', 'Arnod', 'Aroor', 'Arpora', 'Arsikere', 'Arumanai', 'Aruppukottai', 'Arvi', 'Arvi Wardha', 'Arwal', 'Aryanad,Trivandrum', 'Asansol', 'Asansol, West Barddhaman', 'Ashiana nagar Patna', 'Ashoknagar', 'Aspur', 'Assonora', 'At post Unai,ta vansda di navsari', 'Ateli', 'Athani', 'Athazhakunnu', 'Athvelly', 'Atkot', 'Atmakur(man),nellore(dist).', 'Atmakur, MANGALAGIRI', 'Attabira Dist- Bargarh', 'Attingal', 'Attingal,  kochalumoodu', 'Attur', 'Attur, salem', 'Aundh, PUNE', 'Auraiya', 'Aurangabad', 'Aurangbad', 'Auroville', 'Avanigadda', 'Avanyapuram , Madurai', 'Avinashi', 'Avinashi, Tirupur', 'Avinissery PO., Ollur, Trissur district', 'Aya Nagar', 'Ayan kollan kondan (PO) Rajapalayam (TK)', 'Ayodhya', 'Ayodhya Faizabad', 'Ayoor', 'Azamgarh', 'Azheekal Telephone exchange', 'Azhiyur', 'BABA BAKALA', 'BABAI', 'BABARPUR AJITMAL', 'BABEN', 'BABERU', 'BABHALESHWAR', 'BABRA', 'BABRALA', 'BABUGARH', 'BACHELI', 'BACHHRAON', 'BACHRA', 'BADAMI', 'BADARPUR RLY TOWN', 'BADARWAS', 'BADDI', 'BADE BACHELI', 'BADGAM', 'BADHARGHAT', 'BADI', 'BADLAPUR', 'BADLAPUR (East)', 'BADLAPUR (W)', 'BADLAPUR EAST', 'BADLAPUR Road', 'BADLAPUR West', 'BADLAPUR east', 'BADLAPUR, Mumbai', 'BADLI', 'BADNAGAR', 'BADNAGAR Jill Ujjain', 'BADNAPUR', 'BADNAWAR', 'BADRA', 'BADVEL', 'BAGA', 'BAGALKOT', 'BAGASARA', 'BAGDA', 'BAGEPALLI', 'BAGESHWAR', 'BAGGAR', 'BAGHPAT', 'BAGLI', 'BAGNAN', 'BAGRU', 'BAHADARABAD', 'BAHADURGARH', 'BAHADURPUR', 'BAHARAGORA', 'BAHERI', 'BAHIRGRAM', 'BAHJOI', 'BAHRAICH', 'BAIDYABATI', 'BAIHAR', 'BAIKUNTHPUR', 'BAIL HONGAL', 'BAILHONGAL', 'BAIRGANIA', 'BAISINGA', 'BAJNA', 'BAKANI', 'BAKHRI', 'BAKHTIARPUR', 'BAKRESHWAR THERMAL POWER TOWNSHIP', 'BAKSAR', 'BAKSHI KA TALAB', 'BALACHAUR', 'BALAGHAT', 'BALANGIR', 'BALAPALLAM', 'BALAPUR MIDC', 'BALASINOR', 'BALASORE', 'BALESHWAR', 'BALIA', 'BALIAPUR', 'BALICHAK', 'BALIKUDA', 'BALIMELA', 'BALIPARA', 'BALIYASAN', 'BALLABGARH', 'BALLARI', 'BALLARPUR', 'BALLEPALLE', 'BALLIA', 'BALLIKURAVA', 'BALLY', 'BALLY, Bally station', 'BALOD', 'BALODA BAZAR', 'BALOTRA', 'BALRAMPUR', 'BALUGAON', 'BALURGHAT', 'BAMBOLIM', 'BAMBOOFLAT', 'BAMORA', 'BANAGANAPALLE', 'BANAPUR', 'BANASTHALI', 'BANBASA', 'BANDA', 'BANDARULANKA', 'BANDHAWAGARH', 'BANDHBAHAL', 'BANDIA', 'BANDIPUR', 'BANDOAN', 'BANGA', 'BANGALORE', 'BANGALORE CITY 560002', 'BANGALORE NORTH', 'BANGALORE RURAL', 'BANGALORE, KARNATAKA', 'BANGALORE-17', 'BANGALORE18', 'BANGAON', 'BANGARAPET', 'BANGARAPEt', 'BANGUWAN KALAN', 'BANJARA HILLS ,HYDERABAD', 'BANKA', 'BANKAPURA', 'BANKI MONGRA', 'BANKIMNAGAR', 'BANKRA', 'BANKURA', 'BANKURA.', 'BANMANKHI BAZAR', 'BANMOR MORENA', 'BANNUR', 'BANSBERIA', 'BANSDA', 'BANSDIH', 'BANSGAON', 'BANSI', 'BANSWADA', 'BANSWARA', 'BANTVAL', 'BANTWA', 'BANTWAL', 'BANUMUKKALA', 'BANUR', 'BAPATLA', 'BAPUNAGAR,AHMEDABAD', 'BARA GAON', 'BARA JUMLA', 'BARABANKI', 'BARAGAON', 'BARAKAR', 'BARAMATI', 'BARAMKELA', 'BARAMULA', 'BARAN', 'BARAPALI', 'BARARA', 'BARASAT', 'BARASAT - I', 'BARASat', 'BARAULI', 'BARAUNI IOC TOWNSHIP', 'BARAUT', 'BARBIGHA', 'BARBIL', 'BARDEZ', 'BARDHAMAN', 'BARDOLI', 'BAREILLY', 'BAREILLY CANTT', 'BAREJA', 'BARGARH', 'BARGHAT', 'BARGUR', 'BARH', 'BARH, PATNA', 'BARHAJ', 'BARHALGANJ', 'BARHANI BAZAR', 'BARHI', 'BARI', 'BARIPADA', 'BARKAKANA', 'BARKI SARAIYA', 'BARMER', 'BARNALA', 'BARNALa', 'BARODA', 'BAROH', 'BAROTIWALA INDUSTRIAL AREA', 'BARPETA', 'BARPETA ROAD', 'BARRACKPOR', 'BARRACKPORE', 'BARRACKPORE , KOLKATA', 'BARSHI', 'BARSUR', 'BARUGHUTU', 'BARUIPUR', 'BARUNI', 'BARWAHA', 'BARWALA', 'BARWANI', 'BASAVAKALYAN', 'BASAVANA BAGEVADI', 'BASIRHAT', 'BASMATH', 'BASODA', 'BASSEIN', 'BASTI', 'BASUDEBPUR', 'BASUDEBPUR MURSHIDABAD DISTRICT', 'BASUDEBPUR PURBA MEDINIPUR DISTRICT', 'BASUDEBPUR/bhadrak', 'BASUDEVPUR', 'BATALA', 'BATHALAPALLE', 'BATHINDA', 'BATIKA', 'BATLAGUNDU', 'BAVLA', 'BAWAL', 'BAYAD', 'BAYYANAGUDEM', 'BAZPUR', 'BAngalore', 'BCS NEW SHIMLA', 'BEAWAR', 'BEDI', 'BEED', 'BEGAMGANJ', 'BEGOWAL', 'BEGUSARAI', 'BEGUSARAI DISTRICT', 'BEHAT', 'BEHEA', 'BEHRAMPUR', 'BEHROR', 'BELA PRATAPGARH', 'BELA, PRATAPGARH', 'BELAGAVI', 'BELAGAVI Shedbal', 'BELDANGA', 'BELGAUM', 'BELIATORE', 'BELLAMPALLE', 'BELLARY', 'BELPAHAR', 'BELTANGADI', 'BELTHANGADY', 'BELTHARA ROAD', 'BELUR', 'BENAULIM', 'BENGALOORU', 'BENGALORE', 'BENGALUR', 'BENGALURE', 'BENGALURU', 'BENGALURU - 560008', 'BENGALURU -50015', 'BENGALURU 560016', 'BENGALURU 560032', 'BENGALURU 560037', 'BENGALURU 560043', 'BENGALURU 560062', 'BENGALURU 560064', 'BENGALURU 560066', 'BENGALURU 560085', 'BENGALURU 562125', 'BENGALURU EAST', 'BENGALURU NORTH', 'BENGALURU RURAL', 'BENGALURU RURAL DIST', 'BENGALURU,', 'BENGALURU,devnahalli', 'BENGALURU-11', 'BENGALURU-28', 'BENGALURU-560005', 'BENGALURU-560085', 'BENGALURU-560098', 'BENGALURU-97', 'BENGALURU; 560047', 'BENGALURUBangalore', 'BENGALURu', 'BENIPATTI', 'BENIPUR', 'BENUDIA', 'BERHAMPORE', 'BERHAMPUR', 'BERHAMPUR, Ganjam', 'BERI', 'BERMO', 'BESTAWARIPETA', 'BETALBATIM', 'BETTIAH', 'BETUL', 'BETUL BAZAR', 'BEWAR', 'BEYOND 18TH SECTOR,C.H.B.JODHPUR', 'BEYPORE', 'BHABHAR', 'BHABUA', 'BHACHAU', 'BHADERWAH', 'BHADGAON', 'BHADOHI', 'BHADRA', 'BHADRACHALAM', 'BHADRAK', 'BHADRAVATI', 'BHADRESWAR', 'BHAGALPUR', 'BHAGHA PURANA', 'BHAINSA', 'BHAINSDEHI', 'BHAKALI', 'BHAKALI, Rewari', 'BHALKI', 'BHALWAL', 'BHANDARA', 'BHANDARA MIDC', 'BHANDER', 'BHANJANAGAR', 'BHANPURA', 'BHARATGANJ', 'BHARATPUR', 'BHARTHANA', 'BHARUCH', 'BHARWARI', 'BHATAPARA', 'BHATGAON', 'BHATKAL', 'BHATKULI', 'BHATPAR RANI', 'BHATPARA', 'BHAVANI', 'BHAVANISAGAR', 'BHAVNAGAR', 'BHAWAN BAHADUR NAGAR', 'BHAWANI MANDI', 'BHAWANIPATNA', 'BHAYANDER EAST', 'BHEL HARIDWAR', 'BHIKHIWIND', 'BHILAD', 'BHILAI', 'BHILAI  490020', 'BHILAI Charoda', 'BHILAI DURG', 'BHILAI charoda   Dist-durg', 'BHILAI nagar', 'BHILAI-490006, DISTRICT -DURG ,', 'BHILODA', 'BHILWARA', 'BHIMADOLE', 'BHIMAVARAM', 'BHIMAVARAM 2', 'BHIMRAM', 'BHIMTAAL', 'BHIMTAL', 'BHIND', 'BHINDER', 'BHINGA', 'BHINMAL', 'BHITARWAR', 'BHIWADI', 'BHIWANDI', 'BHIWANI', 'BHIWAPUR', 'BHOGAON', 'BHOGNIPUR', 'BHOJPUR', 'BHOKAR', 'BHOLAR DABRI', 'BHONGIR', 'BHOPAL', 'BHOR', 'BHOTA', 'BHOWALI', 'BHUBANESHWAR', 'BHUBANESWAR', 'BHUBANESWAR, Khordha', 'BHUBANESWARB', 'BHUJ', 'BHULEPUR', 'BHUNTAR', 'BHUPALPALLE', 'BHURAGAON', 'BHUSAWAL', 'BHUSAWAL,', 'BHUSHAN STEEL PLANT MERAMANDALI TOWNSHIP', 'BHUVANAGIRI', 'BIAORA', 'BICCAVOLU', 'BICHOLIM', 'BID', 'BIDAR', 'BIDASAR', 'BIDHAN NAGAR', 'BIDHAN NAGAR, Kolkata', 'BIGHAPUR', 'BIHAR BEGUSARAI DISTRICT', 'BIHARSHARIF', 'BIHKA', 'BIHPURIA', 'BIHTA BEGUSARAI DISTRICT', 'BIHTA PATNA DISTRICT', 'BIJAINAGAR AJMER DISTRICT', 'BIJAPUR', 'BIJAULI INDUSTRIAL AREA', 'BIJBEHARA', 'BIJNOR', 'BIJPUR', 'BIJURI', 'BIKANER', 'BIKANER 9680830319', 'BIKAPUR', 'BIKRAM', 'BIKRAMGANJ', 'BILANDAPUR', 'BILASPUR', 'BILASPUR,', 'BILGRAM', 'BILHA', 'BILHAUR', 'BILIMORA', 'BILSI', 'BINA', 'BINDKI', 'BINDKI FATEHPUR', 'BINNAGURI', 'BINOLA INDUSTRIAL AREA', 'BINPUR I', 'BIRAMITRAPUR', 'BIRPARA TEA GARDEN', 'BIRPUR', 'BIRUR', 'BISALPUR', 'BISHAMA KATAK', 'BISHNUGARH', 'BISHNUPUR', 'BISHNUPUR BANKURA DISTRICT', 'BISHRAMPUR', 'BISHUNIPUR', 'BISWAN', 'BISWANATH', 'BISWANATH CHARIALI', 'BIT Campus Mesra, Ranchi', 'BOBBILI', 'BODELI', 'BODH GAYA', 'BODHAN', 'BODINAYAKANUR', 'BODINAYAKANUR, theni dt', 'BODRI', 'BOINPALLE', 'BOISAR', 'BOKAJAN', 'BOKAKHAT', 'BOKARO', 'BOKARO STEEL CITY', 'BOKARO THERMAL', 'BOKARO THERMAL TOWNSHIP', 'BOKARO steel city', 'BOKO', 'BOLPUR', 'BOMDILA', 'BONAIGARH', 'BONGAIGAON', 'BONGAIGAON IOCL TOWNSHIP', 'BONGAIGAON RPCL TOWNSHIP', 'BONGAON', 'BOOTHAPANDI', 'BORAI', 'BORAWAR', 'BORIM', 'BORLI PANCHTAN', 'BORSAD', 'BOTAD', 'BOUDH', 'BRAHMAPURI', 'BRAJARAJNAGAR', 'BUCHIREDDIPALEM', 'BUCHIREDDIPALEM, Nellore', 'BUDAMANGALAM , THIRUVARUR DISTRICT', 'BUDAUN', 'BUDGAM', 'BUDGE BUDGE', 'BUDHANA', 'BUDHLADA', 'BUDNI', 'BUHANA', 'BULANDSHAHR', 'BULDANA', 'BULDHANA', 'BUNDIA', 'BUNGAL', 'BURARI', 'BURDWAN', 'BURHANPUR', 'BURLA', 'BUTIBORI', 'BUTIBORI MIDC', 'BUTIBORI MIDC,', 'BUTTAYAGUDEM', 'BUXAR', 'BYADGI', 'BYASANAGAR', 'Baba Bakala', 'Bachupally', 'Bachupally, Hyderabad', 'Bada bazar SAGAR', 'Badami', 'Baddi Industrial Area', 'Badepalle', 'Badgam', 'Badkagaw', 'Badkulla', 'Badlapur', 'Badlapur (East)', 'Badlapur , Thane', 'Badlapur East', 'Badlapur, Jaunpur', 'Badmal', 'Badsar', 'Badshahpur Gurgaon', 'Badvel', 'Bagaha', 'Bagalkot', 'Bagalkote', 'Bagh amberpet,hyderabad', 'Baghpat (250601)', 'Bagnan', 'Bagodar', 'Baguiati', 'Baguiati Kolkata', 'Baguihati', 'Bahadrabad Gas plant HARIDWAR', 'Bahaduargarh', 'Bahadurgarh', 'Baidyabati, Hooghly', 'Baif road Wagholi pune', 'Baiguinim, Old goa', 'Baithalangso', 'Bajpe', 'Bajrang Nagar Gali no 9 nagpur', 'Bakulia', 'Balaghat', 'Balangir', 'Balapallam', 'Balaramapuram', 'Balaramapuram /mudavoorpara', 'Balarampur Puruliya District', 'Balasore', 'Baldwara', 'Balehonnur', 'Baleshwar', 'Balipatna', 'Balipatna, Khurda', 'Balkum, Thane', 'Ballabgarh', 'Ballabhgarh', 'Ballari', 'Ballia', 'Bally', 'Balodabazar', 'Baloh', 'Balrampur', 'Balurghat', 'Balussery', 'Bambolim', 'Bamor', 'Banagalore', 'Banaganapalli', 'Banaganapalli, kurnool', 'Banaswadi, Bengaluru', 'Banbasa', 'Banda', 'Bande', 'Bandel', 'Bandikui', 'Bandra East, Mumbai', 'Bandra Kurla Complex, Mumbai', 'Bandra West, Mumbai', 'Baner,pune', 'BangaLore', 'Bangalore', 'Bangalore 560062', 'Bangalore 560076', 'Bangalore North', 'Bangalore Rural', 'Bangalore South', 'Bangalore Urban', 'Bangalore north', 'Bangalore,', 'Bangalore-560 086', 'Bangalore-78', 'Bangaluru', 'Banganlore', 'Bangarapet', 'Bangarupalyam', 'Bangihati, Po-Mallickpara,Serampore', 'Bangla chouraha', 'Banglore', 'Bangluru', 'Banka', 'Bankhedi', 'Banki barabanki', 'Bankura', 'Bannanje, UDUPI', 'Banswara', 'Banthra', 'Bantval', 'Bantwal', 'Bantwal T.q.', 'Bantwal Taluk, Dakshina Kannada', 'Bantwal, dakshina kannada', 'Bapatla', 'Bapu Nagar, Sanjeeva Reddy Nagar, HYDERABAD', 'Barabanki', 'Barabungallow', 'Barahat', 'Baramati', 'Baramati,Pune', 'Baramkela', 'Baran', 'Barang, Dadhapatna', 'Barasat', 'Barasst', 'Baraut', 'Barbigha', 'Bardez', 'Bardhaman', 'Bardoli', 'Bareilly', 'Bareli', 'Barendrapara,near-Avinandan Furniture, PO-Sonarpur', 'Bargarh', 'Bargarh District', 'Bargawan', 'Bargur', 'Barh', 'Barhalganj', 'Barkagaw', 'Barmana', 'Barmer', 'Barnala', 'Baroda', 'Barpeta', 'Barpeta Road', 'Barrackpore', 'Basavanabagevadi, VIJAPURA', 'Basirhat', 'Bassi pathana', 'Bassi, JAIPUR', 'Basti', 'Bastora - Mapusa', 'Batala', 'Bathery', 'Bathinda', 'Batika', 'Batlahalli, Chintamani taluk, Chikkaballapur Dist', 'Bavdhan PUNE', 'Bayyanagudem', 'Beas', 'Beawar', 'Beawer', 'Beed', 'Beeri kotekar post', 'Beet bazar', 'Begumpet, Hyderabad', 'Begusarai', 'Behala, KOLKATA', 'Behind ganesh temple, civil line, chandrapur', 'Belagavi', 'Belda', 'Belgaum', 'Belgaum,', 'Belgharia', 'Belgharia Nimta', 'Belgharia, kolkata', 'Belgharia,kolkata', 'Belghoria', 'Belghria', 'Bellare Village and Post', 'Bellary', 'Belthangadi', 'Belthara Road', 'Beltola GUWAHATI', 'Belur', 'Bemili', 'Benaulim', 'Bengaluru', 'Bengaluru 560020', 'Bengaluru South', 'Bengaluru east', 'Bengaluru.', 'Bengoloor', 'Benipatti', 'Benipur', 'Berhampore', 'Berhampur', 'Betalbatim', 'Bethuadahari', 'Bethuadharai', 'Betim,  bardez', 'Bettiah', 'Bettiyah', 'Bhachau', 'Bhadarva', 'Bhadrak', 'Bhagalpur', 'Bhagya nagar,9916015445,Koppal', 'Bhainsa', 'Bhamragad, GADCHIROLI', 'Bhandara', 'Bhandara road', 'Bhandup (west), Mumbai - 400078', 'Bhandup MUMBAI', 'Bhandup east MUMBAI', 'Bhandup- East', 'Bhanger', 'Bharatpur', 'Bharatpur , Bhubaneswar', 'Bharsingi', 'Bharuch', 'Bharuch  Dehgam', 'Bhatapara', 'Bhatgaon', 'Bhatinda', 'Bhatkal', 'Bhatkal-Uttara Kannada', 'Bhatni bazar (Deoria)', 'Bhatpara', 'Bhattanagar .liluah .Howrah', 'Bhavnagar', 'Bhawanipatna', 'Bhayandar (West)', 'Bhayandar east', 'Bhayander (E), Thane', 'Bhayander (Easy)', 'Bhayander East', 'Bhayander west', 'Bheem', 'Bheemunipatanm', 'Bheemunipatnam', 'Bhilai', 'Bhimadole', 'Bhimavaram', 'Bhisiana', 'Bhiwadi', 'Bhiwadi, Alwar', 'Bhiwandi', 'Bhogapuram', 'Bhojipura', 'Bhojipura, Bareilly', 'Bhokar', 'Bhopal', 'Bhoranj', 'Bhosari, Pune', 'Bhosari,pune', 'Bhuban', 'Bhubaneshwar', 'Bhubaneshwar, Odisha', 'Bhubaneswar', 'Bhubaneswar,', 'Bhubaneswar, 751003', 'Bhugaon Mulshi Road', 'Bhugaon, Pune', 'Bhuj', 'Bhunter', 'Bhupalpalle', 'Bhusawal', 'Bibinagar hyderabad', 'Biccavolu', 'Bicholim', 'Bidadi', 'Bidar', 'Bidhan Nagar', 'Bidhan Nagar, Kolkata- 700102', 'Bihar', 'Bihar sharif', 'Bihta', 'Bihta Patna District', 'Bijapur', 'Bijnor', 'Bijpur', 'Bikaner', 'Biknoor', 'Bilaspur', 'Bileipada', 'Bilimora', 'Binnaguri', 'Birati, Kolkata', 'Birbhum', 'Bisalpur', 'Bishnah', 'Bishnupur', 'Biswanath Chariali', 'Biswanath chariali, Biswanath', 'Bodakdev, Ahmedabad', 'Boduppal', 'Boduppal, Hyderabad - 92', 'Boinchi', 'Bokakhat', 'Bokaro Steel City', 'Bokaro steel city', 'Bolpur', 'Bommuru rajahmundry', 'Bonaigarh', 'Bonda,Banarpal', 'Bongaigaon', 'Bopal ahmedabad', 'Bopodi Pune', 'Bordi', 'Borivali (W), MUMBAI', 'Borivali East', 'Borivali East, Mumbai', 'Borivali West MUMBAI', 'Borivali West, Mumbai', 'Borivali west, Munbai', 'Borivali,Mumbai', 'Borivali-west, MUMBAI', 'Borka', 'Brahmapur', 'Brahmavar', 'Brahmavar, Udupi', 'Bramhapuri', 'Brg Shangri-La  Ind

In [69]:
df["ship-city"].value_counts().head(100)

ship-city
BENGALURU    11216
HYDERABAD     8074
MUMBAI        6126
NEW DELHI     5795
CHENNAI       5421
             ...
KAKINADA       145
Lucknow        144
GWALIOR        144
Ghaziabad      142
AMRITSAR       142
Name: count, Length: 100, dtype: int64

In [70]:
df["ship-city"] = df["ship-city"].str.strip()
df["ship-city"] = df["ship-city"].str.title()

In [71]:
df["ship-city"] = df["ship-city"].str.replace(r"\s+", " ")

In [75]:
df["ship-city"].value_counts().head(100)

ship-city
Bengaluru             11897
Hyderabad              9125
Mumbai                 7122
New Delhi              6340
Chennai                6284
Pune                   4616
Kolkata                2844
Gurugram               1954
Thane                  1877
Noida                  1627
Lucknow                1627
Ghaziabad              1484
Ahmedabad              1444
Navi Mumbai            1403
Bangalore              1362
Jaipur                 1062
Coimbatore              891
Visakhapatnam           858
Faridabad               820
Patna                   816
Bhubaneswar             780
Pimpri Chinchwad        754
Guwahati                740
Nagpur                  732
Vadodara                710
Thiruvananthapuram      679
Dehradun                633
Secunderabad            621
Surat                   564
Greater Noida           564
Indore                  557
Kalyan                  547
Kanpur                  541
Ernakulam               517
Bhopal                  502
Ranchi                  482
Vijayawada              479
Mysuru                  423
Guntur                  422
Varanasi                387
Nashik                  380
Delhi                   361
Mangaluru               358
Gurgaon                 338
Vasai Virar             331
Chandigarh              324
Allahabad               324
Jamshedpur              306
Thrissur                295
Nellore                 286
Mohali                  285
Jammu                   277
Madurai                 276
Gorakhpur               260
Puducherry              260
Agra                    252
New Town                249
Tirupati                247
Kozhikode               245
Meerut                  242
Palakkad                240
Ludhiana                233
Howrah                  225
Rajkot                  218
Imphal                  217
Warangal                217
Raipur                  216
Udaipur                 212
Jalandhar               212
Kottayam                206
Kochi                   203
Cuttack                 202
Jabalpur                194
Tiruchirappalli         193
Siliguri                189
Vellore                 183
Port Blair              180
Jodhpur                 177
Aurangabad              177
Udupi                   174
Srinagar                173
Kollam                  172
Salem                   171
Amritsar                166
Bareilly                164
Kakinada                161
Gwalior                 159
Kolhapur                153
Pathanamthitta          153
Zirakpur                152
Shimla                  150
Panchkula               149
Dimapur                 147
Anantapur               146
Hubballi                143
Haldwani                141
Belagavi                137
Gandhinagar             136
Durgapur                134
Kannur                  134
Name: count, dtype: int64

In [74]:
pd.set_option('display.max.rows',100)

In [ ]:
df["ship-city"] = df["ship-city"].str.strip()
df["ship-city"] = df["ship-city"].str.title()
city_replace = {
    "Bangalore": "Bengaluru",
    "Gurgaon": "Gurugram",
    "Delhi": "New Delhi",
    "Allahabad": "Prayagraj"
}

df["ship-city"] = df["ship-city"].replace(city_replace)

In [48]:
df.to_csv("C:/Documents/Data analysis/Project/Amazon_Sales_Clean.csv", index=False)
print("✅ Cleaned dataset exported successfully!")

✅ Cleaned dataset exported successfully!